import type { Metadata } from "next";
import { Inter, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const pleMono = IBM_Plex_Mono({
  variable: "--font-inter",
  subsets: ["latin"],
  weight:['400', '500']
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${inter.variable} ${pleMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
